apiVersion: spaces.tanzu.vmware.com/v1alpha1
kind: Space
metadata:
  name: mbentley-space
  namespace: default
spec:
  availabilityTargets:
    - name: mbentley-home-at
      replicas: 2
  revisionHistoryLimit: 10
  template:
    spec:
      profiles:
        - name: mbentley-profile
          values:
            inline: null
      resources: {}
  updateStrategy:
    type: RollingUpdate
