apiVersion: spaces.tanzu.vmware.com/v1alpha1
kind: Profile
metadata:
  name: mbentley-profile
  namespace: default
spec:
  description: Matt's profile
  requiredCapabilities:
    - name: certificates.tanzu.vmware.com
    - name: container-app.tanzu.vmware.com
    - name: package-management.tanzu.vmware.com
    - name: k8sgateway.tanzu.vmware.com
  traits:
    - alias: carvel-package-installer.tanzu.vmware.com
      name: carvel-package-installer.tanzu.vmware.com
      values:
        inline:
          carvel-package-installer:
            serviceAccountName: carvel-package-installer
