apiVersion: spaces.tanzu.vmware.com/v1alpha1
kind: AvailabilityTarget
metadata:
  name: mbentley-lab-at
  namespace: default
  resourceVersion: "21582504"
  uid: eb0264b9-3e21-4055-a4ba-ce7fe1bd2b32
spec:
  affinity:
    clusterAffinity:
      clusterSelectorTerms:
        - matchExpressions:
            - key: mbentley-env
              operator: In
              values:
                - lab
    clusterAntiAffinity:
      clusterSelectorTerms: []
  description: mbentley lab at
